### ISSUE TITLE
Rename repo to match changed ID com.itextpdf.RUPS

### ISSUE THREAD

**Issue by nbenitez** [flathub/com.github.itext.i7j_rups#2]
@barthalion  I think I need your help here, iText representative gave permission to use the official **com.itextpdf.RUPS** ID. So I just merged a change for that, but now app cannot be built because the repo name is the old one **com.github.itext.i7j_rups** and I cannot change it.

Please rename this repo to match new ID **com.itextpdf.RUPS**

Thanks!

**Comment by barthalion** [comment]
Yeah, I mean, I told during review to use it from the beginning. At this point you'll need to submit it as new app and mark the old one as EOL with https://github.com/flathub/flathub/wiki/App-Maintenance#end-of-life
